#!/usr/bin/env perl
$latex            = 'platex -kanji=utf8 -guess-input-enc -synctex=1';
$latex_silent     = 'platex -kanji=utf8 -guess-input-enc -synctex=1 -interaction=batchmode';
$bibtex           = 'pbibtex -kanji=utf8';
$dvipdf           = 'dvipdfmx %O -o %D %S';
$makeindex        = 'mendex %O -o %D %S';
$max_repeat       = 5;
$pdf_mode         = 3; # generates pdf via dvipdfmx

# auto update
#$pdf_update_method = 4;
#$pdf_update_command = "open -a Preview %S"

# Prevent latexmk from removing PDF after typeset.
# This enables Skim to chase the update in PDF automatically.
$pvc_view_file_via_temporary = 0;

# Use Skim as a previewer
if ($^O eq 'darwin') {
	$pdf_previewer    = "open -ga /Applications/Skim.app";
} elsif ($^O eq 'linux') {
	$pdf_previewer = 'evince';
}
