#!/bin/bash
#
# usage:
#   check_tmux_check
#
# description:
#   check whether tmux plugin installed
#
# return:
#    0: succeed
#    1: failed

# MAIN SCRIPT
#
# main function
ret=0
declare -a actual=()
declare -a expect=()

COMMAND="set -g @plugin 'tmux-plugins/"


# installed tmux plugin
for LINE in `ls -l ~/.tmux/plugins/ | awk '$1 ~ /d/ {print $9 }'`
do
	acutual=(${actual[@]} ${LINE})
done

# expect to install tmux plugin
while read LINE
do
	if [[ $LINE =~ ${COMMAND}(.*)\' ]]; then
		expect=(${BASH_REMATCH[1]} ${expect[@]})
	fi
done < ~/.tmux.conf

for e in ${actual[@]}; do
	actual=("${actual[@]:1}")
	echo ${expect[@]} | grep ${e} > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		echo "Not Found: ${e}"
		ret=1
	fi
done

exit $ret
