" GVimのメニューバー文字化け対策
source $VIMRUNTIME/delmenu.vim
set langmenu=ja_jp.utf-8
source $VIMRUNTIME/menu.vim

"英語メッセージにする
if has("multi_lang")
language C
endif

"半角文字の設定
set guifont=Ricty_Diminished_for_Powerline:h12
"全角文字の設定
set guifontwide=Ricty_Diminished_for_Powerline:h12

" カラースキームの設定
autocmd ColorScheme * highlight Comment ctermfg=darkgray
colorscheme molokai

" タブバーを常に表示
set showtabline=2

" メニューバー、ツールバー、スクロールバーを非表示
set guioptions+=lrbmTLce
set guioptions-=lrbmTLce
set guioptions+=c
