" Generic configuration
set scrolloff=5
syntax enable
colorscheme desert
set number
set ruler
set notitle
set list
set listchars=tab:»-,trail:-,extends:»,precedes:«,nbsp:%
set laststatus=2
set cmdheight=1
set showcmd
set cursorline
set matchpairs& matchpairs+=<:>
set showmatch
set wrap
set shiftround
set infercase
set hidden
set switchbuf=useopen
set autoread
set tabstop=8
set shiftwidth=8
set smarttab
set smartindent
set ambiwidth=double

" charset
set encoding=utf-8
scriptencoding utf-8
set fileencoding=utf-8
set fileencodings=utf-8,euc-jp,iso-20220-jp
set termencoding=utf-8

" Interface
set backspace=indent,eol,start
set clipboard+=unnamed
set mouse=a
set vb t_vb=
set novisualbell

" Metafile for Vim
set noswapfile
set nobackup
set noundofile

" search
set ignorecase
set smartcase
set incsearch
set hlsearch
set wrapscan
set wildmenu wildmode=list:full
