#!/bin/bash
#
# usage:
#   deinstall
#
# description:
#   install dein and vim plugin
#
# return:
#    0: succeed
#    1: failed install

# MAIN SCRIPT                          
# -------------------------------------
# this script needs one more arguments.

yes | timeout -sKILL 60 nvim +:q
echo "vim plugin installed"

timeout -sKILL 5 nvim +:q
if [ $? != 0 ]; then 
# タイムアウトしたときの処理
  exit 1
fi

echo "completed install vim plugins"
exit 0
