# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install depends packages
        run: |
          sudo apt-get update
          sudo apt-get install git make curl wget vim neovim ctags global zsh 

      - name: Clean develop environments
      - run:  make clean

      - name: Install each dotfiles
      - run:  make install

      - name: Check whether each dotfiles is installed
      - run:  make test

      - name: Check whether vim plugins is installed
      - run:  ./tests/check_vim_plugin

      - name: Check vim performance
      - run:  ./script/overhead_vim
